### ISSUE TITLE
Your spec facility alphabetizes method names

### ISSUE THREAD

**Issue by rmoskal** [mkwiatkowski/pinocchio#23]
This test class:    

    class TestKonfigure(unittest.TestCase):

        def test_handles_special_environment_mapping(self):
            pass

        def test_fails_when_mapping_undefined(self):
            pass

        def test_atf(self):
            pass

results in:

    Konfigure
    - atf
    - fails when mapping undefined
    - handles special environment mapping

This one:

    class TestKonfigure(unittest.TestCase):

        def test_handles_special_environment_mapping(self):
            pass

        def test_fails_when_mapping_undefined(self):
            pass

        def test_wtf(self):
            pass

results in:

    Konfigure
    - fails when mapping undefined
    - handles special environment mapping
    - wtf

**Comment by mkwiatkowski** [comment]
It's the test runner, spec plugin outputs lines in the order the tests are run.

**Comment by rmoskal** [comment]
Ha you're right!  That's even more screwed up :)  Kind of sucks.

**Comment by mkwiatkowski** [comment]
Order of tests shouldn't matter. If you care about it though you can try using something like https://pypi.python.org/pypi/nose-order-plugin
