### ISSUE TITLE
Status of this project and PyPI use

### ISSUE THREAD

**Issue by nim65s** [mkwiatkowski/pinocchio#28]
Hi  @mkwiatkowski,

I was wondering if this project is still actively used.

I am a member of another project that share the same name: https://github.com/stack-of-tasks/pinocchio/ .
We provide releases for this project under this name in various ecosystems, as AUR, conda, homebrew, robotpkg, and ROS.

I also have some manylinux wheels ready to be published, but since you already registered the name on PyPI, it's a bit tricky. 

As the latest commit here is from 5 years ago, and the latest release on PyPI is even older than this, could you consider archiving this project, and releasing the "pinocchio" name on PyPI, or do you plan to keep using it ?

**Comment by mkwiatkowski** [comment]
Hi @nim65s,

According to https://pypistats.org/packages/pinocchio the package is still being downloaded, so presumably used by someone. Scraping it and replacing with a different package may break things for some people, and I don't want to do that. Please register your project under a new name.
