### ISSUE TITLE
Django.test.TestCase docstring pollutes test name discovery

### ISSUE THREAD

**Issue by kortesmv-etasku** [mkwiatkowski/pinocchio#29]
Using Python 3.8 Django 2.2.17 and pinocchio 0.4.2,

the --with-spec method no longer picks up test case names as descriptions, but instead every test gets the inherited docstring from django TestCase as the name. Is there any way to turn docstring usage off, or detect this base class and filter it out?

The string is multiline 

```
Similar to TransactionTestCase, but use `transaction.atomic()` to achieve
test isolation.

In most situations, TestCase should be preferred to TransactionTestCase as
it allows faster execution. However, there are some situations where using
TransactionTestCase might be necessary (e.g. testing some transactional
behavior).

On database backends with no transaction support, TestCase behaves as
TransactionTestCase.
```

**Comment by mkwiatkowski** [comment]
There is no configuration in pinocchio that would disable that behavior, as currently docstrings take precedence over method names: https://github.com/mkwiatkowski/pinocchio/blob/master/pinocchio/spec.py#L203-L218

However there is a workaround. If you override docstring in your test case to be an empty string it will work as you want. Something like this:

```python
class YourTestCase(django.test.TestCase):
  ""
  ...
```

Let me know if that works.

**Comment by kortesmv-etasku** [comment]
It works, but it's a bit labour intensive (modifying ~60 files).

**Comment by mkwiatkowski** [comment]
Yeah, that's rough. I agree it's a bug. It doesn't make sense for specs to inherit docstrings from superclasses. I will prepare a fix.

**Comment by mkwiatkowski** [comment]
Sorry for the delay. The PR is at #30. Please install it locally and see if that fix works for you. If so I'll merge and release a new version to PyPI.

**Comment by kortesmv-etasku** [comment]
Works nicely. Thank you!

**Comment by mkwiatkowski** [comment]
Great. I released a new version of pinocchio to PyPI: https://pypi.org/project/pinocchio/0.4.3/
