### ISSUE TITLE
AttributeError: module 'pinocchio' has no attribute 'SE3'

### ISSUE THREAD

**Issue by dqj5182** [mkwiatkowski/pinocchio#31]
Can I know how to solve this issue?

**Comment by 2021270902001sc** [comment]
You and I both made a mistake with Pinocchio. Their official project is here（https://github.com/stack-of-tasks/pinocchio/）, and someone registered it on PyPI ahead of time.

**Comment by dqj5182** [comment]
Oh! Thanks for letting me know!
